Update pywin32
26.09 packages this version already as it didn't use the lock file. We need to match that version now because otherwise Windows Installer does not update some files if they have lower version numbers: https://learn.microsoft.com/en-us/archive/blogs/astebner/why-windows-installer-removes-files-during-a-major-upgrade-if-they-go-backwards-in-version-numbers

Anki 26.09.1 fails with this error at startup:
```
Traceback (most recent call last):
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app\anki\__main__.py", line 21, in <module>
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app\anki\app.py", line 6, in main
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app_packages\aqt\__init__.py", line 90, in <module>
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app_packages\aqt\main.py", line 25, in <module>
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app_packages\aqt\sound.py", line 25, in <module>
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app_packages\aqt\mpv.py", line 68, in <module>
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app_packages\win32\lib\pywintypes.py", line 124, in <module>
  File "D:\a\anki\anki\out\installer\build\anki\windows\visualstudio\x64\Release\app_packages\win32\lib\pywintypes.py", line 50, in __import_pywin32_system_module__
ModuleNotFoundError: No module named '_win32sysloader'
```