Fix compilation under rust 1.89
Rust 1.89 produces the following output:

```
error: unicode codepoint changing visible direction of text present in literal
...
warning: allow(text_direction_codepoint_in_literal) is ignored unless specified at crate level
 --> rslib/i18n/src/generated.rs:7:10
  |
7 | #![allow(text_direction_codepoint_in_literal)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This change fixes it.

This ensures that some third-party crate that pulls in this code as
library code (and thus isn't subject to the rust-toolchain file in this
repo) doesn't hit this compilation error.