Revert "fix TypeError: channel.execCallbacks[message.id] is not a function"
This reverts commit 331239de05cdb5c734a694f312b7534fd005e0c6.

This commit caused the blur event from the editor to fire after the saveNow()
callback had run, which broke the reviewer when returning from editcurrent.
Reverting for now, as the actual error is harmless AFAICT.